[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['DATABASE_URL=$DATABASE_PUBLIC_URL npx prisma migrate deploy', 'DATABASE_URL=$DATABASE_PUBLIC_URL npm run build']

[start]
cmd = 'npm start'
